sudo: false
language: python
cache:
  directories:
  - "$HOME/gcloud/"
env:
- PATH=$PATH:$HOME/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_45d1b36fa803_key -iv $encrypted_45d1b36fa803_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d $HOME/google-cloud-sdk ]; then  
    curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- gcloud auth activate-service-account --key-file client-secret.json
install:
- gcloud config set compute/zone us-central1-b
- gcloud config set project continuous-deployment-python
- gcloud -q components update gae-python
- pip install -r requirements.txt -t lib/
script:
- gcloud -q preview app deploy app.yaml --set-default 
- python e2e_test.py
